#extensions
dot racket: ".rkt"
dot rust: ".rs"
dot pie: ".py"
dot talon: ".talon"
dot mark down: ".md"
dot shell: ".sh"
dot vim: ".vim"
dot see: ".c"
dot see sharp: ".cs"
flabber: ".com"
dot net: ".net"
dot org: ".org"
dot exe: ".exe"
dot (bin | bend): ".bin"	
dot (jason | jay son): ".json"
dot racket: ".rkt"